### ISSUE TITLE
Refresh for gmxapi 0.4

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi-tutorials#10]
With https://gitlab.com/gromacs/gromacs/-/merge_requests/3314, the tutorial material should work just fine with any GROMACS build (but may need some updates). We should resume our attempt to merge to the tutorials.gromacs.org site and refresh the Spack-built and container based application environments, such as have been used for past workshops and HPC application gateways.

## TODO

- [ ] Establish a Spack recipe
- [ ] Test and update the material for gmxapi 0.4
- [ ] Test and integrate with the tutorials.gromacs.org environment. May require
    - [ ] Test/debug installation against a Conda gromacs package.
